(()=>{
'use strict';
const frame=()=>document.getElementById('pci');
const ACTIVE_KEY='pciActiveSchoolV1',NAMES_KEY='pciSchoolNamesV1',STATE_PREFIX='pciSchoolStateV1:';
const SCHOOLS=[['PCI-101','Escuela 1'],['PCI-102','Escuela 2'],['PCI-103','Escuela 3'],['PCI-104','Escuela 4']];
let overlay;
const valid=code=>SCHOOLS.some(([c])=>c===code);
const active=()=>localStorage.getItem(ACTIVE_KEY)||'';
const names=()=>{try{return JSON.parse(localStorage.getItem(NAMES_KEY)||'{}')}catch{return {}}};
const schoolName=code=>names()[code]||SCHOOLS.find(([c])=>c===code)?.[1]||code;
const stateKey=code=>STATE_PREFIX+code;
const emptyState=()=>JSON.stringify({areas:{},current:null,schemaVersion:7});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveSnapshot(){const code=active();if(code)localStorage.setItem(stateKey(code),localStorage.getItem('pciAppV2')||emptyState())}
function activate(code){if(!valid(code))return;const prev=active();if(prev&&prev!==code)saveSnapshot();localStorage.setItem(ACTIVE_KEY,code);localStorage.setItem('pciAppV2',localStorage.getItem(stateKey(code))||emptyState())}
function setName(code,value){const all=names(),clean=String(value||'').trim();if(clean)all[code]=clean;else delete all[code];localStorage.setItem(NAMES_KEY,JSON.stringify(all));renderOverlay();decorateFrame()}
function schoolHref(code){return `plataforma.html?school=${encodeURIComponent(code)}&v=12`}
function renderOverlay(){if(!overlay)return;const current=active();overlay.querySelector('[data-school-list]').innerHTML=SCHOOLS.map(([code,fallback])=>`<article class="school-card ${current===code?'selected':''}"><div class="school-open"><strong>${code}</strong><span>${esc(schoolName(code)||fallback)}</span>${current===code?'<em>PCI activo</em>':''}</div><label>Nombre de la escuela<input data-school-name="${code}" value="${esc(schoolName(code))}"></label><a class="school-enter" href="${schoolHref(code)}">Entrar</a></article>`).join('');overlay.querySelectorAll('[data-school-name]').forEach(input=>input.onchange=()=>setName(input.dataset.schoolName,input.value))}
function openOverlay(){ensureOverlay();renderOverlay();overlay.classList.add('open')}
function closeOverlay(){overlay?.classList.remove('open')}
function ensureOverlay(){if(overlay)return overlay;const style=document.createElement('style');style.textContent=`.school-overlay{position:fixed;inset:0;z-index:2147483000;background:#f4f7f8ee;display:none;overflow:auto;padding:24px;font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#15374a}.school-overlay.open{display:block}.school-shell{width:min(920px,100%);margin:4vh auto;background:#fff;border:1px solid #dbe5e8;border-radius:24px;padding:22px;box-shadow:0 24px 70px #15374a26}.school-head{display:flex;justify-content:space-between;gap:12px}.school-head h1{margin:0}.school-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.school-card{border:2px solid #dbe5e8;border-radius:17px;padding:10px;background:#fff}.school-card.selected{border-color:#83ded3}.school-open{background:#f8fbfb;border-radius:13px;padding:14px}.school-open strong{display:block;font-size:.8rem;color:#167557}.school-open span{display:block;font-size:1.05rem;font-weight:900;margin-top:3px}.school-open em{display:inline-block;margin-top:7px;padding:4px 7px;border-radius:999px;background:#e5f6ef;color:#167557;font-size:.7rem;font-style:normal;font-weight:900}.school-card label{display:grid;gap:5px;font-size:.73rem;font-weight:850;margin-top:9px}.school-card input{width:100%;box-sizing:border-box;border:1px solid #dbe5e8;border-radius:10px;padding:9px;background:#fff}.school-enter{display:block;text-align:center;text-decoration:none;margin-top:10px;border-radius:11px;padding:11px 12px;background:#15374a;color:#fff;font-weight:900}.school-close{border:0;border-radius:12px;padding:9px 12px;font-weight:900;background:#e7edef;color:#15374a}@media(max-width:650px){.school-overlay{padding:10px}.school-list{grid-template-columns:1fr}}`;document.head.appendChild(style);overlay=document.createElement('section');overlay.className='school-overlay';overlay.innerHTML=`<div class="school-shell"><div class="school-head"><div><h1>Seleccionar PCI institucional</h1><p>Elegí una escuela para ingresar a su matriz.</p></div><button class="school-close" type="button" data-school-close>Cerrar</button></div><div class="school-list" data-school-list></div></div>`;document.body.appendChild(overlay);overlay.querySelector('[data-school-close]').onclick=closeOverlay;return overlay}
function decorateFrame(){const d=frame()?.contentDocument,code=active();if(!d||!code)return;const actions=d.querySelector('.top .actions');if(actions){let b=d.getElementById('schoolSwitcher');if(!b){b=d.createElement('button');b.id='schoolSwitcher';b.className='btn';b.type='button';b.onclick=openOverlay;actions.insertBefore(b,actions.firstChild)}b.textContent=`${code} · ${schoolName(code)}`}}
function boot(){const requested=new URLSearchParams(location.search).get('school');if(valid(requested)){activate(requested);history.replaceState(null,'','plataforma.html')}ensureOverlay();const f=frame();if(active()){const saved=localStorage.getItem(stateKey(active()));if(saved)localStorage.setItem('pciAppV2',saved);if(f)f.src=`app.html?school=${encodeURIComponent(active())}&t=${Date.now()}`}else openOverlay();f?.addEventListener('load',()=>setTimeout(decorateFrame,300));setInterval(decorateFrame,1000);addEventListener('beforeunload',saveSnapshot)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();