(()=>{
'use strict';
const frame=()=>document.getElementById('pci');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function state(){const w=frame()?.contentWindow;if(!w)return null;try{return {w,DATA:w.DATA||w.eval('DATA'),CFG:w.CFG||w.eval('CFG'),app:w.app||w.eval('app')}}catch{return null}}
function schoolLabel(){const code=localStorage.getItem('pciActiveSchoolV1')||'';let names={};try{names=JSON.parse(localStorage.getItem('pciSchoolNamesV1')||'{}')}catch{}return {code,name:names[code]||code||'PCI'}}
function reportData(){const s=state();if(!s||!Array.isArray(s.DATA)||!s.DATA.length){alert('La base todavía está cargando. Esperá unos segundos y volvé a intentar.');return null}const rows=[];for(const area of Object.keys(s.CFG||{})){const data=s.app?.areas?.[area],all=s.DATA.filter(x=>x.area===area);for(const x of all){const groups=data?(data.groups||[]).filter(g=>(g.items||[]).includes(x.id)).map(g=>g.name):[];rows.push({area,subject:x.subject,axis:x.axis,text:x.text,groups:groups.length?groups.join(' · '):'Pendiente'})}}return {...s,rows}}
function tableHTML(rows){return `<h2>Tabla de control</h2><table><thead><tr><th>Área</th><th>Materia</th><th>Eje/Bloque</th><th>Contenido priorizado</th><th>Agrupamiento donde quedó</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.area)}</td><td>${esc(r.subject)}</td><td>${esc(r.axis||'')}</td><td>${esc(r.text)}</td><td class="${r.groups==='Pendiente'?'pending':''}">${esc(r.groups)}</td></tr>`).join('')}</tbody></table>`}
function styles(){return `body{font-family:Arial,sans-serif;color:#15374a;margin:22px}h1{margin-bottom:4px}h2{border-bottom:2px solid #83ded3;padding-bottom:5px}.summary{display:flex;gap:20px;flex-wrap:wrap;background:#edf5f6;padding:12px;border-radius:10px;margin:12px 0 18px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #b9c7cc;padding:5px;text-align:left;vertical-align:top}th{background:#edf5f6}.pending{color:#9a6500;font-weight:bold}.tools{position:sticky;top:0;background:white;padding:10px 0;display:flex;justify-content:flex-end;gap:8px}.tools button{border:0;border-radius:10px;padding:10px 14px;background:#15374a;color:white;font-weight:bold;cursor:pointer}.tools .download{background:#83ded3;color:#15374a}.credit{text-align:center;color:#687985;margin-top:28px}@media print{.tools{display:none}body{margin:8mm}}`}
function downloadXLS(){const R=reportData();if(!R)return;const school=schoolLabel();const rows=R.rows.map(r=>`<tr><td>${esc(r.area)}</td><td>${esc(r.subject)}</td><td>${esc(r.axis||'')}</td><td>${esc(r.text)}</td><td>${esc(r.groups)}</td></tr>`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><style>table{border-collapse:collapse}th,td{border:1px solid #999;padding:5px;vertical-align:top}th{background:#dceff0}</style></head><body><h1>Tabla de control · ${esc(school.name)} · ${esc(school.code)}</h1><table><thead><tr><th>Área</th><th>Materia</th><th>Eje/Bloque</th><th>Contenido priorizado</th><th>Agrupamiento donde quedó</th></tr></thead><tbody>${rows}</tbody></table></body></html>`;const blob=new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`Tabla_de_control_${school.code||'PCI'}.xls`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
function openControl(){const R=reportData();if(!R)return;const school=schoolLabel(),assigned=R.rows.filter(r=>r.groups!=='Pendiente').length,win=window.open('','_blank');if(!win){alert('El navegador bloqueó la ventana. Habilitá ventanas emergentes.');return}window.pciDownloadControlXLS=downloadXLS;win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Tabla de control · ${esc(school.code)}</title><style>${styles()}</style></head><body><div class="tools"><button class="download" onclick="opener.pciDownloadControlXLS()">Descargar XLS</button><button onclick="print()">Imprimir / Guardar PDF</button></div><h1>Tabla de control · ${esc(school.name)} · ${esc(school.code)}</h1><div class="summary"><b>${assigned} contenidos asignados</b><b>${R.rows.length-assigned} pendientes</b><b>${R.rows.length} contenidos totales</b></div>${tableHTML(R.rows)}<p class="credit">Matriz PCI</p></body></html>`);win.document.close();win.focus()}
function install(){const d=frame()?.contentDocument;if(!d)return;const actions=d.querySelector('.top .actions');if(!actions||d.getElementById('openControlTable'))return;const btn=d.createElement('button');btn.id='openControlTable';btn.className='btn';btn.type='button';btn.textContent='Tabla de control';btn.onclick=openControl;const map=d.getElementById('openMap');if(map)actions.insertBefore(btn,map.nextSibling);else actions.insertBefore(btn,actions.firstChild)}
frame()?.addEventListener('load',()=>setTimeout(install,500));setInterval(install,1000);
})();